#!/usr/bin/env python3
"""
Trade Hunter Distribution Script
Generates a "Public Edition" of the codebase by stripping commercial-only features.
Usage: python scripts/distribute.py
"""

import os
import shutil
import sys
from pathlib import Path

# Configuration
ROOT = Path(__file__).parent.parent.resolve()
DIST_ROOT = ROOT / "dist"
PUBLIC_DIR = DIST_ROOT / "trade-hunter-public"

# Files/Folders to completely ignore during copy
IGNORE_PATTERNS = [
    ".git",
    ".github",
    ".home",
    ".pytest_cache",
    ".venv",
    ".vscode",
    "__pycache__",
    ".env",
    ".env.example",  # Keep private env examples out if needed
    "dist",
    "scratch",
    "tests",         # Optional: keep public repo light
    ".gsd",          # Private milestone tracking
    ".antigravity_session",
]

# Sensitive files to physically DELETE from the public copy
STRIP_FILES = [
    "app/feeds/kalshi_pykalshi.py",
]

def main():
    print("--- Trade Hunter Distribution Tool ---")
    
    if os.path.exists(PUBLIC_DIR):
        print(f"Cleaning existing dist folder: {PUBLIC_DIR}")
        shutil.rmtree(PUBLIC_DIR)
    
    os.makedirs(DIST_ROOT, exist_ok=True)
    
    print(f"Syncing master -> {PUBLIC_DIR}...")
    
    def ignore_func(directory, contents):
        return [c for c in contents if c in IGNORE_PATTERNS or c.endswith(".pyc")]

    shutil.copytree(ROOT, PUBLIC_DIR, ignore=ignore_func)
    
    print("Patching Edition Configuration...")
    edition_path = PUBLIC_DIR / "app" / "edition.py"
    if edition_path.exists():
        with open(edition_path, "w", encoding="utf-8") as f:
            f.write("# Trade Hunter Public Edition\n")
            f.write("# AUTO-GENERATED BY DISTRIBUTE.PY\n")
            f.write("IS_COMMERCIAL = False\n")
        print("[OK] IS_COMMERCIAL set to False.")
    else:
        print("[WARN] WARNING: app/edition.py not found in public copy!")

    print("Stripping Commercial-Only Source Files...")
    for rel_path in STRIP_FILES:
        target = PUBLIC_DIR / rel_path
        if target.exists():
            target.unlink()
            print(f"[OK] Stripped: {rel_path}")
            # Create a placeholder if needed
            placeholder = target.with_suffix(".py.restricted")
            placeholder.write_text("# This module is exclusive to the Commercial Edition.\n# Visit https://tradehunter.ai to upgrade.\n")
        else:
            print(f"[WARN] WARNING: Sensitive file not found: {rel_path}")

    print("\nSUCCESS!")
    print(f"Your Public Edition is ready at: {PUBLIC_DIR}")
    print("You can now push the contents of this folder to your public GitHub repository.")

if __name__ == "__main__":
    main()
