#!/usr/bin/env python3
"""
Trade Hunter Distribution Script
Generates a "Public Edition" of the codebase by stripping commercial-only features.
Usage: python scripts/distribute.py
"""

from __future__ import annotations

import fnmatch
import os
import shutil
from pathlib import Path

# Configuration
ROOT = Path(__file__).parent.parent.resolve()
DIST_ROOT = ROOT / "dist"
PUBLIC_DIR = DIST_ROOT / "trade-hunter-public"

# ── IGNORE_PATTERNS (public Edition export) ───────────────────────────────
# shutil.copytree `ignore=` only inspects entry *names* in each directory walk.
#
# IGNORE_NAMES — exact basename (file or folder) skipped everywhere.
IGNORE_NAMES = frozenset({
    # VCS / tool / env hygiene
    ".git",
    ".github",  # commercial CI and copilot configs; omit from public tarball
    ".home",
    ".pytest_cache",
    ".venv",
    ".vscode",
    "__pycache__",
    ".env",
    # Output / ephemeral / workspace cruft from local runs
    "dist",
    "scratch",
    "tests",  # keep public checkout light (no bundled pytest fixtures)
    "build",
    "tmp",
    ".tmp",
    ".artifacts",
    # Private agent + milestone metadata (commercial repo continuity)
    ".gsd",
    ".gsd-id",
    ".gsd.migrating",
    ".antigravity_session",
    ".holistic",
    ".planning",
    ".cursor",
    ".beads",
    # IDE / toolchain rules wired to authors' setups
    ".cursorrules",
    ".windsurfrules",
    # Repo-local secrets or integration scratch (never distribute)
    ".bg-shell",
    ".kalshi-keys",
    # Ephemeral notebooks / probes (not docs)
    "current_feeds.txt",
    "proposal_feeds.txt",
    "HANDOFF.md",
    # Generated / leaked local artefacts (explicit names often present at repo root)
    "trade_hunter.egg-info",
    "integration_test_results.md",
    "integration_test_results_sqlite.md",
    "output.log",
    "trade-hunter-boot.log",
    "design-proposal.html",
    "trade-hunter_dashboard_mockup.html",
    # Agent protocol copies at repo root (keep README/DEPLOYMENT/USER_GUIDE)
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
    "HOLISTIC.md",
})

# IGNORE_NAME_GLOBS — fnmatch on basename (per-directory entry names).
IGNORE_NAME_GLOBS: tuple[str, ...] = (
    "trade-hunter*.exe",
    "trade_hunter.corrupt*.db",
    "*.pyc",
    # Local SQLite WAL / SHM / backups from dev machines
    "trade_hunter.db-shm",
    "trade_hunter.db-wal",
    "trade_hunter.db.bak-*",
    "trade_hunter.db",
    # PyInstaller / frozen-build spec files (commercial packaging)
    "trade-hunter*.spec",
)

# Basenames that are always ignored *except* we still allow .env.example for OSS.
def _ignore_basename(name: str) -> bool:
    if name in IGNORE_NAMES:
        return True
    for pattern in IGNORE_NAME_GLOBS:
        if fnmatch.fnmatch(name, pattern):
            return True
    return False


# Commercial-only source files removed after copy (replaced with .py.restricted stub)
STRIP_FILES = [
    "app/feeds/kalshi_pykalshi.py",
]


def main():
    print("--- Trade Hunter Distribution Tool ---")

    if os.path.exists(PUBLIC_DIR):
        print(f"Cleaning existing dist folder: {PUBLIC_DIR}")
        shutil.rmtree(PUBLIC_DIR)

    os.makedirs(DIST_ROOT, exist_ok=True)

    print(f"Syncing master -> {PUBLIC_DIR}...")

    def ignore_func(directory, contents):
        return [c for c in contents if _ignore_basename(c)]

    shutil.copytree(ROOT, PUBLIC_DIR, ignore=ignore_func)

    print("Patching Edition Configuration...")
    edition_path = PUBLIC_DIR / "app" / "edition.py"
    if edition_path.exists():
        with open(edition_path, "w", encoding="utf-8") as f:
            f.write("# Trade Hunter Public Edition\n")
            f.write("# AUTO-GENERATED BY DISTRIBUTE.PY\n")
            f.write("IS_COMMERCIAL = False\n")
        print("[OK] IS_COMMERCIAL set to False.")
    else:
        print("[WARN] WARNING: app/edition.py not found in public copy!")

    print("Stripping Commercial-Only Source Files...")
    for rel_path in STRIP_FILES:
        target = PUBLIC_DIR / rel_path
        if target.exists():
            target.unlink()
            print(f"[OK] Stripped: {rel_path}")
            placeholder = target.with_suffix(".py.restricted")
            placeholder.write_text(
                "# This module is exclusive to the Commercial Edition.\n"
                "# Visit https://tradehunter.ai to upgrade.\n"
            )
        else:
            print(f"[WARN] WARNING: Sensitive file not found: {rel_path}")

    print("\nSUCCESS!")
    print(f"Your Public Edition is ready at: {PUBLIC_DIR}")
    print("You can now push the contents of this folder to your public GitHub repository.")


if __name__ == "__main__":
    main()
